name: LuckBot
version: '${project.version}'
main: fr.gglinnk.luckbot.LuckBot
api-version: 1.18
author: GGLinnk
authors: [ GGLinnk ]
description: '${project.description}'
website: https://gglinnk.virtualworld.fr/project/luckbot
depend: [ LuckPerms ]
